# Generated by Django 4.1.7 on 2023-07-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0002_profile_bio_profile_fb_profile_insta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_desc', models.TextField(max_length=2000)),
                ('post_quote', models.TextField(max_length=1000)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='image/post')),
                ('post_tag', models.CharField(choices=[('tech', 'Tech'), ('green', 'Green'), ('yellow', 'Yellow')], max_length=100)),
                ('post_read_min', models.CharField(max_length=50)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authapp.profile')),
            ],
        ),
    ]
