# Generated by Django 4.1.7 on 2023-07-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_profile_bio_profile_fb_profile_insta_and_more'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_tag',
            field=models.CharField(choices=[('tech', 'TECH'), ('food', 'FOOD'), ('spritual', 'SPRITUAL'), ('fitness', 'FITNESS'), ('motivation', 'MOTIVATION'), ('politics', 'POLITICS'), ('movies', 'MOVIES'), ('music', 'MUSIC')], max_length=100),
        ),
    ]
